name: merge_group

on:
  pull_request:
  merge_group:
  
jobs:
  main:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "${{ toJSON(github) }}"
