name: merge_group

on:
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "${{ toJSON(github) }}"
