name: merge_group

on:
  merge_group:
    types: [ checks_requested ]
    branches:
      - main
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "${{ toJSON(github) }}"
