name: update-acl

on:
  issues:
    types:
      - labeled

jobs:
  check_permission:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: check privilege
        run: |
          echo "${{github.event.sender.login}}"

  parse_info:
    needs: [check_permission]
    runs-on: ubuntu-latest
    outputs:
      file_path: ${{ steps.main.outputs.file_path }}
      level: ${{ steps.main.outputs.level }}
      github_username: ${{ steps.main.outputs.github_username }}
      discord_username: ${{ steps.main.outputs.discord_username }}
    steps:
      - id: main
        shell: bash
        run: |
          body="${{ github.event.issue.body }}"
          body=${body//$'\r'/}
          body=${body//$'\n'/}
          body=${body//$'\r\n'/}
          regex="### GitHub Username[\r|\n|\r\n]*([0-9a-zA-Z-]*)[\r|\n|\r\n]*### Discord ID[\r|\n|\r\n]*(.{3,32}#[0-9]{4})"
          if [[ ! $body =~ $regex ]]; then
            echo "failed to parse issue body: $body"
            exit 1
          fi
          github_username="${BASH_REMATCH[1]}"
          discord_username="${BASH_REMATCH[2]}"
          echo "github_username=github_username" >> $GITHUB_OUTPUT
          echo "discord_username=$discord_username" >> $GITHUB_OUTPUT

          title="${{ github.event.issue.title }}"
          regex="Request (.*) access for (.*) to the (.*)"
          if [[ ! $title =~ $regex ]]
          then
            echo "failed to parse issue title: $title"
            exit 1
          else
            privilege="${BASH_REMATCH[1]}"
            repo="${BASH_REMATCH[3]}"

            file_path=
            case `echo $repo | sed -e 's/^[[:space:]]*//'` in
              "Solana Labs Monorepo")
                file_path=access-control-list/monorepo-member-access.md
              ;;
              "SPL repository")
                file_path=access-control-list/spl-member-access.md
              ;;
              *)
                exit 1
              ;;
            esac
            echo "file_path=$file_path" >> $GITHUB_OUTPUT

            level=
            case $privilege in
              "Triage")
                level=1
              ;;
              "Write")
                level=2
              ;;
              *)
                exit 1
              ;;
            esac
            echo "level=$level" >> $GITHUB_OUTPUT
          fi

  update_acl:
    needs: [parse_info]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: needs.parse_info.outputs.level == 1
        run: |
          git remote
          echo "level1"

      - if: needs.parse_info.outputs.level == 2
        run:
          echo "level2"
